# Netlify build instructions
[build]
    command = "./docs/book/build.sh"
    publish = "docs/book/book"

# Standard Netlify redirects
[[redirects]]
    from = "https://kubernetes-sigs-image-builder.netlify.com//*"
    to = "https://image-builder.sigs.k8s.io/:splat"
    status = 301
    force = true

# HTTP-to-HTTPS rules
[[redirects]]
    from = "http://image-builder.sigs.k8s.io/*"
    to = "https://image-builder.sigs.k8s.io/:splat"
    status = 301
    force = true

[[redirects]]
    from = "http://kubernetes-sigs-image-builder.netlify.com/*"
    to = "http://image-builder.sigs.k8s.io/:splat"
    status = 301
    force = true
