[book]
authors = ["The Image Builder Maintainers"]
language = "en"
multilingual = false
src = "src"
title = "The Image Builder Book"

[output.html]
curly-quotes = true
git-repository-url = "https://sigs.k8s.io/image-builder"
