apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/kubernetes-sigs/cluster-api-provider-azure/releases/download/v1.6.0/cluster-template.yaml
patchesStrategicMerge:
- ../patches/azuremachinetemplate-controlplane.yaml
- ../patches/azuremachinetemplate-workload.yaml